# Generated by Django 5.0.3 on 2024-04-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_book_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.writer'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='pic',
            field=models.FileField(default='writer/writer.png', upload_to='writer/'),
        ),
    ]
