# Generated by Django 5.0.3 on 2024-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_book_writer_alter_writer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
